import { ChatProvider } from '@context/chat'
import { Toast } from '@ui/toast'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'AI Chat',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <ChatProvider>
        <body className='h-screen bg-dark-primary text-white dark:text-black'>
          <Toast />
          {children}
        </body>
      </ChatProvider>
    </html>
  )
}
